### PR TITLE
#41 fix lock button

### LINKED ISSUE #41: The tx button isn't properly reactive
Adding an amount to lock doesn't 'refresh' the disabled attribute properly

### PR DESCRIPTION
**Pull request by hardingjam**
closes #41

### CODE REVIEW

File: src/lib/components/Lock.svelte [hunk 1]
```diff
@@ -63,6 +65,8 @@
 	onDestroy(() => {
 		stopGettingPriceRatio();
 	});
+
+	$: console.log('insufficientFunds', insufficientFunds, 'assets', assets);
```
Comment (hardyjosh) [inline src/lib/components/Lock.svelte:69]: console log

**Review by hardyjosh — APPROVED** [review]
